1. Reading a dataset into a dataframe

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("weather.csv")
print(df)
df.head(10)

    MinTemp  MaxTemp  Rainfall  ...  Temp3pm  RainToday  RainTomorrow
0       8.0     24.3       0.0  ...     23.6         No           Yes
1      14.0     26.9       3.6  ...     25.7        Yes           Yes
2      13.7     23.4       3.6  ...     20.2        Yes           Yes
3      13.3     15.5      39.8  ...     14.1        Yes           Yes
4       7.6     16.1       2.8  ...     15.4        Yes            No
..      ...      ...       ...  ...      ...        ...           ...
94     17.1     29.6       0.0  ...     29.1         No           Yes
95     18.2     22.6       1.8  ...     22.1        Yes           Yes
96     16.8     22.8       9.0  ...     21.5        Yes            No
97     13.6     27.4       1.0  ...     26.5         No            No
98     14.5     24.2       0.0  ...     20.3         No           Yes

[99 rows x 15 columns]

   MinTemp  MaxTemp  Rainfall  ...  Temp3pm  RainToday  RainTomorrow
0      8.0     24.3       0.0  ...     23.6         No           Yes
1     14.0     26.9       3.6  ...     25.7        Yes           Yes
2     13.7     23.4       3.6  ...     20.2        Yes           Yes
3     13.3     15.5      39.8  ...     14.1        Yes           Yes
4      7.6     16.1       2.8  ...     15.4        Yes            No
5      6.2     16.9       0.0  ...     14.8         No            No
6      6.1     18.2       0.2  ...     17.3         No            No
7      8.3     17.0       0.0  ...     15.5         No            No
8      8.8      NaN       0.0  ...     18.9         No           Yes
9      8.4     22.8      16.2  ...     21.7        Yes            No

[10 rows x 15 columns]

2. Dropping rows with missing(”NaN”) values

In [4]:
df.dropna("rows")

    MinTemp  MaxTemp  Rainfall  ...  Temp3pm  RainToday  RainTomorrow
0       8.0     24.3       0.0  ...     23.6         No           Yes
1      14.0     26.9       3.6  ...     25.7        Yes           Yes
2      13.7     23.4       3.6  ...     20.2        Yes           Yes
5       6.2     16.9       0.0  ...     14.8         No            No
7       8.3     17.0       0.0  ...     15.5         No            No
10      9.1     25.2       0.0  ...     24.0         No            No
12     10.1     27.9       0.0  ...     27.1         No            No
13     12.1     30.9       0.0  ...     30.7         No            No
15     12.4     32.1       0.0  ...     30.7         No            No
16     13.8     31.2       0.0  ...     29.8         No           Yes
22     12.8     18.5      25.8  ...     16.8        Yes            No
23     12.0     24.3       0.4  ...     22.8         No            No
26     13.3     22.2       0.2  ...     21.2         No            No
27     12.9     28.0       0.0  ...     26.7         No            No
28     15.1     24.3       0.0  ...     19.7         No            No
30     15.1     20.4      22.6  ...     16.3        Yes           Yes
31     11.6     26.3       4.2  ...     25.2        Yes            No
32     16.6     24.2       0.2  ...     19.9         No           Yes
33     13.3     26.5       6.6  ...     25.1        Yes            No
36     17.2     25.8       0.0  ...     22.6         No           Yes
38     15.0     29.4       0.0  ...     28.6         No            No
39     14.9     24.8       0.0  ...     22.9         No            No
40     11.8     18.5       0.6  ...     16.4         No            No
44     10.1     29.9       0.0  ...     29.1         No           Yes
45     15.5     21.1       5.4  ...     20.0        Yes           Yes
46     10.8     21.7       1.4  ...     20.8        Yes            No
47      7.5     20.9       0.0  ...     19.8         No            No
48     12.8     21.0       0.0  ...     20.0         No           Yes
50     14.8     29.5       6.4  ...     28.2        Yes           Yes
52      9.2     20.4      17.4  ...     18.8        Yes            No
53     12.4     24.4       0.0  ...     22.5         No           Yes
56     14.3     26.7       0.0  ...     19.0         No           Yes
57     15.1     28.3      14.4  ...     27.4        Yes            No
59     15.4     35.0       0.0  ...     34.3         No            No
60     13.8     33.5       0.0  ...     32.2         No            No
61     13.6     34.2       0.0  ...     31.8         No            No
63     15.9     23.4       0.0  ...     22.3         No            No
65     12.1     27.5       0.0  ...     26.8         No            No
67     16.5     33.9       0.0  ...     31.3         No            No
70     14.7     34.2       0.0  ...     32.2         No            No
72     20.9     35.7       0.0  ...     34.0         No           Yes
73     17.0     33.8       2.0  ...     31.8        Yes            No
74     16.0     22.8       0.0  ...     21.6         No            No
75     15.4     33.8       0.0  ...     31.7         No            No
80     17.2     24.7      12.2  ...     21.9        Yes            No
81     15.9     19.9       0.8  ...     18.6         No            No
82     10.0     22.5       0.0  ...     22.2         No            No
83      9.9     24.4       0.0  ...     22.7         No            No
86     12.7     28.8       0.0  ...     28.3         No            No
87     13.2     31.3       0.0  ...     30.7         No            No
91     17.6     27.8       5.2  ...     26.3        Yes           Yes
93     14.9     28.8       0.0  ...     27.0         No            No
95     18.2     22.6       1.8  ...     22.1        Yes           Yes
96     16.8     22.8       9.0  ...     21.5        Yes            No
98     14.5     24.2       0.0  ...     20.3         No           Yes

[55 rows x 15 columns]

3. Dropping columns with missing(”NaN”) values

In [5]:
df.dropna("columns")

    MinTemp  Rainfall  Evaporation  Cloud9am  Cloud3pm RainToday RainTomorrow
0       8.0       0.0          3.4         7         7        No          Yes
1      14.0       3.6          4.4         5         3       Yes          Yes
2      13.7       3.6          5.8         8         7       Yes          Yes
3      13.3      39.8          7.2         2         7       Yes          Yes
4       7.6       2.8          5.6         7         7       Yes           No
..      ...       ...          ...       ...       ...       ...          ...
94     17.1       0.0          5.8         6         7        No          Yes
95     18.2       1.8          8.0         8         8       Yes          Yes
96     16.8       9.0          2.8         8         8       Yes           No
97     13.6       1.0          2.8         4         7        No           No
98     14.5       0.0          6.8         7         7        No          Yes

[99 rows x 7 columns]

4. Filling the ”Nan” values with mean, median

In [6]:
df.fillna(df.mean())
df.fillna(df.median())

    MinTemp  MaxTemp  Rainfall  ...  Temp3pm  RainToday  RainTomorrow
0       8.0     24.3       0.0  ...     23.6         No           Yes
1      14.0     26.9       3.6  ...     25.7        Yes           Yes
2      13.7     23.4       3.6  ...     20.2        Yes           Yes
3      13.3     15.5      39.8  ...     14.1        Yes           Yes
4       7.6     16.1       2.8  ...     15.4        Yes            No
..      ...      ...       ...  ...      ...        ...           ...
94     17.1     29.6       0.0  ...     29.1         No           Yes
95     18.2     22.6       1.8  ...     22.1        Yes           Yes
96     16.8     22.8       9.0  ...     21.5        Yes            No
97     13.6     27.4       1.0  ...     26.5         No            No
98     14.5     24.2       0.0  ...     20.3         No           Yes

[99 rows x 15 columns]

5. Split data set by row and column wise

In [9]:
#Split values by a character:

print(df.RainToday.str.split('e').str[0].tolist())
print(df.RainToday.str.split('e').str[1].tolist())

['No', 'Y', 'Y', 'Y', 'Y', 'No', 'No', 'No', 'No', 'Y', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Y', 'No', 'No', 'No', 'No', 'Y', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Y', 'Y', 'No', 'Y', 'No', 'No', 'No', 'Y', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Y', 'Y', 'No', 'No', 'Y', 'Y', 'Y', 'Y', 'No', 'Y', 'No', 'No', 'Y', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Y', 'No', 'No', 'No', 'Y', 'No', 'Y', 'Y', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Y', 'Y', 'No', 'No', 'Y', 'Y', 'No', 'No']
[nan, 's', 's', 's', 's', nan, nan, nan, nan, 's', nan, nan, nan, nan, nan, nan, nan, 's', nan, nan, nan, nan, 's', nan, nan, nan, nan, nan, nan, nan, 's', 's', nan, 's', nan, nan, nan, 's', nan, nan, nan, nan, nan, nan, nan, 's', 's', nan, nan, 's', 's', 's', 's', nan, 's', nan, nan, 's', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 's', nan, nan, nan, 's', nan, 's', 's', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 's', 's', nan, nan, 's', 's', nan, nan]